"""
Django settings for InternshipPortal project.

Generated by 'django-admin startproject' using Django 6.0.1.
"""

import pymysql
pymysql.install_as_MySQLdb()

from pathlib import Path
import os
from dotenv import load_dotenv
import json
import boto3

BASE_DIR = Path(__file__).resolve().parent.parent
# Load .env file - works both in Docker (/app/.env) and locally
env_path = os.path.join(BASE_DIR, '.env')
if not os.path.exists(env_path):
    # Fallback to InternshipPortal/.env for local development
    env_path = os.path.join(BASE_DIR, 'InternshipPortal', '.env')
load_dotenv(env_path, override=True)

# Function to fetch secrets from AWS Secrets Manager
def get_secret(secret_name, region='ap-south-1'):
    """Fetch secret from AWS Secrets Manager, fallback to environment variables"""
    try:
        client = boto3.client('secretsmanager', region_name=region)
        response = client.get_secret_value(SecretId=secret_name)
        return json.loads(response['SecretString'])
    except Exception as e:
        print(f"Warning: Could not fetch secret from Secrets Manager: {e}")
        return {}

# Try to fetch secrets from AWS Secrets Manager (in K8s/EKS)
# Fallback to .env variables for local development
secrets = get_secret('internship-portal-secrets') if os.getenv('AWS_ROLE_ARN') else {}

SECRET_KEY = secrets.get("SECRET_KEY") or os.getenv("SECRET_KEY", 'django-insecure-%#gakond4hg%q#aa(5h8&4i-43(nzjbntobpeuxoc_x8%#aw)0')

DEBUG = False
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000  # Support large CSV uploads

# Build ALLOWED_HOSTS from environment or use defaults
allowed_hosts_env = os.getenv('ALLOWED_HOSTS', '')
if allowed_hosts_env:
    ALLOWED_HOSTS = [host.strip() for host in allowed_hosts_env.split(',')]
else:
    ALLOWED_HOSTS = []

# Ensure our domain is always included
ALLOWED_HOSTS.extend([
    'internship.rubixeprojects.com',
    'www.internship.rubixeprojects.com',
    'rubixeprojects.com',
    '127.0.0.1',
    'localhost',
    '*',
])

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_apscheduler',
    'Submissions',
    'ControlCenter',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # WhiteNoise for static files
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',  # harmless even if you don't use passwords
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'InternshipPortal.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',  # ok even if not using auth login
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'InternshipPortal.wsgi.application'

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": secrets.get("DB_NAME") or os.getenv("DB_NAME"),
        "USER": secrets.get("DB_USER") or os.getenv("DB_USER"),
        "PASSWORD": secrets.get("DB_PASSWORD") or os.getenv("DB_PASSWORD"),
        "HOST": secrets.get("DB_HOST") or os.getenv("DB_HOST", "localhost"),
        "PORT": secrets.get("DB_PORT") or os.getenv("DB_PORT", "3306"),
        "OPTIONS": {
            "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}

# Password validators can remain; using Django auth login anyway
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Password hashers: support both new (Argon2) and old hashes for backward compatibility
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',      # New default (secure)
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',      # Old Django default (for backward compat)
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',  # Very old Django
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher', # If BCrypt was used
]

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

REDIS_ENABLED = os.getenv('REDIS_ENABLED', 'False').lower() == 'true'

if REDIS_ENABLED:
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': os.getenv('REDIS_URL', 'redis://internship-redis:6379/0'),
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                'CONNECTION_POOL_KWARGS': {
                    'max_connections': 50,
                    'health_check_interval': 30,
                },
                'SOCKET_CONNECT_TIMEOUT': 5,
                'SOCKET_TIMEOUT': 5,
                'COMPRESSOR': 'django_redis.compressors.zlib.ZlibCompressor',
            }
        }
    }
    # Sessions in Redis (faster than DB)
    SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
    SESSION_CACHE_ALIAS = 'default'
else:
    # Fallback to database cache if Redis unavailable
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
            'LOCATION': 'django_cache_table',
        }
    }
    SESSION_ENGINE = 'django.contrib.sessions.backends.db'

# ==================== LOGGING CONFIGURATION ====================
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} {module} {funcName}:{lineno} - {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'simple': {
            'format': '{levelname} - {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'django.log'),
            'maxBytes': 10485760,  # 10MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'cache_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'cache.log'),
            'maxBytes': 5242880,  # 5MB
            'backupCount': 3,
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': os.getenv('LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
        'Submissions': {
            'handlers': ['console', 'file'],
            'level': os.getenv('LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
        'cache': {
            'handlers': ['console', 'cache_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'django_redis': {
            'handlers': ['console', 'cache_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

# Ensure logs directory exists
os.makedirs(os.path.join(BASE_DIR, 'logs'), exist_ok=True)

# Static
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# Media ( REQUIRED FOR FileField uploads)
# Configure S3 for EKS, local file system for development
USE_S3 = os.getenv('USE_S3', 'False').lower() == 'true'

if USE_S3:
    # AWS S3 Configuration (for EKS/production)
    AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKET_NAME', 'internship7portal')
    AWS_S3_REGION_NAME = os.getenv('AWS_S3_REGION_NAME', 'ap-south-1')
    AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com'
    AWS_S3_OBJECT_PARAMETERS = {'CacheControl': 'max-age=86400'}
    AWS_DEFAULT_ACL = 'private'
    AWS_LOCATION = 'media'  # S3 key prefix for uploaded files
    AWS_QUERYSTRING_AUTH = False  # Don't add query string auth to URLs

    # S3 media settings
    MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/media/'

    # MEDIA_ROOT is used as a local disk fallback when a file is missing from S3.
    # Set MEDIA_ROOT in .env to the server path where local evaluation files are stored.
    # If not set, falls back to BASE_DIR/media (same default as local dev).
    _env_media_root = os.getenv('MEDIA_ROOT', '')
    MEDIA_ROOT = _env_media_root if _env_media_root else os.path.join(BASE_DIR, 'media')
else:
    # Local file system (for local development/Docker Compose)
    MEDIA_URL = "/media/"
    # Use /app/media in Docker, /DarkSpace/InternshipPortal/media on host
    if os.path.exists("/app"):
        MEDIA_ROOT = "/app/media"
    else:
        MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# WhiteNoise Configuration - serve media files in production
WHITENOISE_MIMETYPES = {
    '.docx': 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    '.pdf': 'application/pdf',
}
WHITENOISE_USE_FINDERS = True
WHITENOISE_AUTOREFRESH = True

# Default PK type (recommended)
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django 4+ Storage Configuration (STORAGES overrides DEFAULT_FILE_STORAGE)
if USE_S3:
    # AWS S3 Storage for Django 4+
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
else:
    # Local file system storage
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }

# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = secrets.get('GMAIL_USER') or os.getenv('GMAIL_EMAIL')
EMAIL_HOST_PASSWORD = secrets.get('GMAIL_PASSWORD') or os.getenv('GMAIL_PASSWORD')
DEFAULT_FROM_EMAIL = secrets.get('GMAIL_USER') or os.getenv('GMAIL_EMAIL')

# API Keys Configuration (with fallback to .env)
GROQ_API_KEY1 = secrets.get('GROQ_API_KEY1') or os.getenv('GROQ_API_KEY1')
GROQ_API_KEY2 = secrets.get('GROQ_API_KEY2') or os.getenv('GROQ_API_KEY2')
GEMINI_API_KEY1 = secrets.get('GEMINI_API_KEY1') or os.getenv('GEMINI_API_KEY1')
GEMINI_API_KEY2 = secrets.get('GEMINI_API_KEY2') or os.getenv('GEMINI_API_KEY2')

# Session Security
SESSION_COOKIE_HTTPONLY = True  # Prevent JavaScript access
SESSION_COOKIE_SECURE = False  # Set to False for local HTTP testing
SESSION_COOKIE_SAMESITE = 'Lax'  # CSRF protection
SESSION_COOKIE_AGE = 1800  # 30 minutes
SESSION_SAVE_EVERY_REQUEST = True  # Update session on every request

# CSRF Configuration - Add trusted origins for Cloudflare domain
CSRF_TRUSTED_ORIGINS = [
    'https://internship.rubixeprojects.com',
    'https://www.internship.rubixeprojects.com',
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'http://localhost:8001',
    'http://127.0.0.1:8001',
]

# Cloudflare Proxy Configuration
# Trust X-Forwarded-Proto header from Cloudflare to detect HTTPS
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Security Headers
# SECURE_SSL_REDIRECT disabled - Cloudflare already handles HTTPS redirect + enforcement
# This allows WhiteNoise to serve media files without forcing HTTPS
SECURE_SSL_REDIRECT = False
SECURE_HSTS_SECONDS = 31536000  # 1 year
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

