# Generated by Django 6.0.1 on 2026-01-12 11:28

import Submissions.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentIdentity',
            fields=[
                ('email', models.EmailField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'student_identity',
            },
        ),
        migrations.CreateModel(
            name='ProjectRegistry',
            fields=[
                ('project_id', models.CharField(db_column='ProjectID', max_length=50, primary_key=True, serialize=False)),
                ('course', models.CharField(db_column='Course', max_length=120)),
                ('project_name', models.CharField(db_column='ProjectName', max_length=255)),
                ('project_type', models.CharField(choices=[('Capstone', 'Capstone'), ('Client', 'Client')], db_column='ProjectType', max_length=20)),
                ('dataset_link', models.URLField(blank=True, db_column='DatasetLink', max_length=1000, null=True)),
                ('llm_input_prompt', models.TextField(blank=True, db_column='LLMInputPrompt', null=True)),
                ('expected_submission', models.JSONField(blank=True, db_column='ExpectedSubmissionJSON', null=True)),
            ],
            options={
                'db_table': 'project_registry',
                'indexes': [models.Index(fields=['course'], name='project_reg_Course_fdcaf4_idx'), models.Index(fields=['project_type'], name='project_reg_Project_7d20af_idx')],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('course', models.CharField(db_column='course', max_length=120)),
                ('status', models.CharField(choices=[('Registered', 'Registered'), ('TeamIDGiven', 'TeamIDGiven'), ('CapStoneProjectsAssigned', 'CapStoneProjectsAssigned'), ('ClientProjectAssigned', 'ClientProjectAssigned')], db_column='status', default='Registered', max_length=40)),
                ('identity', models.ForeignKey(db_column='email', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='Submissions.studentidentity')),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('student', models.OneToOneField(db_column='email', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='team', serialize=False, to='Submissions.studentidentity')),
                ('team_preference', models.BooleanField(db_column='TeamPreference', default=False)),
                ('team_id', models.CharField(db_column='TeamID', max_length=50, unique=True)),
                ('team_count', models.PositiveIntegerField(db_column='TeamCount', default=0)),
            ],
            options={
                'db_table': 'team',
                'indexes': [models.Index(fields=['team_id'], name='team_TeamID_b96d7c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('submission_link', models.URLField(blank=True, db_column='submission_link', max_length=1000, null=True)),
                ('evaluated', models.BooleanField(db_column='evaluated', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('project', models.ForeignKey(db_column='ProjectID', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='Submissions.projectregistry')),
                ('student', models.ForeignKey(db_column='student_enrollment_id', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='Submissions.student')),
                ('team', models.ForeignKey(db_column='TeamID', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='Submissions.team', to_field='team_id')),
            ],
            options={
                'db_table': 'submission',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='team',
            field=models.ForeignKey(blank=True, db_column='TeamID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='Submissions.team', to_field='team_id'),
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('course', models.CharField(db_column='course', max_length=120)),
                ('evaluation_report', models.TextField(blank=True, db_column='evaluation_report', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('project', models.ForeignKey(db_column='ProjectID', on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='Submissions.projectregistry')),
                ('team', models.ForeignKey(db_column='TeamID', on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='Submissions.team', to_field='team_id')),
            ],
            options={
                'db_table': 'evaluation',
            },
        ),
        migrations.CreateModel(
            name='SubmissionFile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=Submissions.models.submission_upload_path)),
                ('original_name', models.CharField(blank=True, max_length=300, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='Submissions.submission')),
            ],
            options={
                'db_table': 'submission_file',
                'indexes': [models.Index(fields=['uploaded_at'], name='submission__uploade_27b456_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['evaluated'], name='submission_evaluat_048494_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['created_at'], name='submission_created_152927_idx'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('team', 'project'), name='uniq_submission_team_project'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['course'], name='student_course_4409ff_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['status'], name='student_status_bbc24a_idx'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('identity', 'course'), name='uniq_student_email_course'),
        ),
        migrations.AddIndex(
            model_name='evaluation',
            index=models.Index(fields=['course'], name='evaluation_course_19b4ba_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluation',
            index=models.Index(fields=['created_at'], name='evaluation_created_d26ee3_idx'),
        ),
        migrations.AddConstraint(
            model_name='evaluation',
            constraint=models.UniqueConstraint(fields=('team', 'project'), name='uniq_evaluation_team_project'),
        ),
    ]
