# Generated by Django 6.0.1 on 2026-01-12 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Submissions', '0002_rename_evaluation_course_19b4ba_idx_submissions_course_6e60a0_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamProject',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('project_type', models.CharField(blank=True, choices=[('Capstone', 'Capstone'), ('Client', 'Client')], db_column='ProjectType', max_length=20, null=True)),
                ('status', models.CharField(choices=[('assigned', 'assigned'), ('submitted', 'submitted'), ('evaluated', 'evaluated')], db_column='status', default='assigned', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True, db_column='assigned_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'submissions_team_project',
            },
        ),
        migrations.RemoveConstraint(
            model_name='submission',
            name='uniq_submission_team_project',
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('Registered', 'Registered'), ('TeamIDGiven', 'TeamIDGiven'), ('CapStoneProjectsAssigned', 'CapStoneProjectsAssigned'), ('ClientProjectAssigned', 'ClientProjectAssigned'), ('AllCompleted', 'AllCompleted')], db_column='status', default='Registered', max_length=40),
        ),
        migrations.AddField(
            model_name='teamproject',
            name='project',
            field=models.ForeignKey(db_column='ProjectID', on_delete=django.db.models.deletion.CASCADE, related_name='team_projects', to='Submissions.projectregistry'),
        ),
        migrations.AddField(
            model_name='teamproject',
            name='team',
            field=models.ForeignKey(db_column='TeamID', on_delete=django.db.models.deletion.CASCADE, related_name='team_projects', to='Submissions.team', to_field='team_id'),
        ),
        migrations.AddField(
            model_name='submission',
            name='team_project',
            field=models.ForeignKey(blank=True, db_column='team_project_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='Submissions.teamproject'),
        ),
        migrations.RemoveField(
            model_name='submission',
            name='project',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='team',
        ),
        migrations.AddIndex(
            model_name='teamproject',
            index=models.Index(fields=['status'], name='submissions_status_a2d043_idx'),
        ),
        migrations.AddIndex(
            model_name='teamproject',
            index=models.Index(fields=['assigned_at'], name='submissions_assigne_42d6b0_idx'),
        ),
        migrations.AddConstraint(
            model_name='teamproject',
            constraint=models.UniqueConstraint(fields=('team', 'project'), name='uniq_team_project'),
        ),
    ]
