# Generated by Django 6.0.1 on 2026-01-13 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Submissions', '0003_teamproject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectregistry',
            name='project_document',
            field=models.FileField(blank=True, db_column='ProjectDocument', help_text='Project specification, guidelines, or instructions (PDF, DOCX, etc.)', null=True, upload_to='project_docs/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('Registered', 'Registered'), ('TeamIDGiven', 'TeamIDGiven'), ('CapStoneProjectsAssigned', 'CapStoneProjectsAssigned'), ('ReadyForClientPick', 'ReadyForClientPick'), ('ClientProjectAssigned', 'ClientProjectAssigned'), ('AllCompleted', 'AllCompleted')], db_column='status', default='Registered', max_length=40),
        ),
    ]
