# Generated by Django 6.0.1 on 2026-01-19 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Submissions', '0008_alter_team_model_for_multi_member_teams'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('email', models.EmailField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('evaluator', 'Evaluator')], default='admin', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'submissions_admin_user',
            },
        ),
        migrations.RemoveIndex(
            model_name='team',
            name='submissions_TeamID_5d5c67_idx',
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='team',
            field=models.ForeignKey(db_column='TeamID', on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='Submissions.team'),
        ),
        migrations.AlterField(
            model_name='student',
            name='team',
            field=models.ForeignKey(blank=True, db_column='TeamID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='Submissions.team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_id',
            field=models.CharField(db_column='TeamID', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teamproject',
            name='team',
            field=models.ForeignKey(db_column='TeamID', on_delete=django.db.models.deletion.CASCADE, related_name='team_projects', to='Submissions.team'),
        ),
    ]
