# Generated by Django 6.0.1 on 2026-01-19 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Submissions', '0009_adminuser_remove_team_submissions_teamid_5d5c67_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='password',
            field=models.CharField(default='@internship123', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adminuser',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('student', 'Student')], default='student', max_length=20),
        ),
        migrations.AddIndex(
            model_name='adminuser',
            index=models.Index(fields=['is_active'], name='submissions_is_acti_7faccf_idx'),
        ),
        migrations.AddIndex(
            model_name='adminuser',
            index=models.Index(fields=['email'], name='submissions_email_13127a_idx'),
        ),
        migrations.AddIndex(
            model_name='adminuser',
            index=models.Index(fields=['username'], name='submissions_usernam_715780_idx'),
        ),
    ]
