# Generated by Django 6.0.1 on 2026-02-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Submissions', '0011_evaluation_reviewed_evaluation_reviewed_at'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='student',
            new_name='submissions_course_a0a6af_idx',
            old_name='submissions_course_9ee8fc_idx',
        ),
        migrations.RenameIndex(
            model_name='student',
            new_name='submissions_status_4933c9_idx',
            old_name='submissions_status_f508f9_idx',
        ),
        migrations.AddField(
            model_name='studentidentity',
            name='NOC_issued',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='studentidentity',
            name='portal_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterModelTable(
            name='student',
            table='submissions_class StudentIdentity',
        ),
    ]
