# Generated by Django 6.0.1 on 2026-02-03 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Submissions', '0012_rename_submissions_course_9ee8fc_idx_submissions_course_a0a6af_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='student',
            new_name='submissions_course_9ee8fc_idx',
            old_name='submissions_course_a0a6af_idx',
        ),
        migrations.RenameIndex(
            model_name='student',
            new_name='submissions_status_f508f9_idx',
            old_name='submissions_status_4933c9_idx',
        ),
        migrations.AlterModelTable(
            name='student',
            table='submissions_student',
        ),
    ]
