# Generated by Django 6.0.1 on 2026-02-03 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Submissions', '0013_rename_submissions_course_a0a6af_idx_submissions_course_9ee8fc_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('otp_code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'submissions_password_reset_otp',
                'indexes': [models.Index(fields=['email', 'is_used'], name='submissions_email_578f70_idx')],
            },
        ),
    ]
