# Generated by Django 6.0.1 on 2026-02-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Submissions', '0014_passwordresetotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(db_column='code', max_length=10, unique=True)),
                ('name', models.CharField(db_column='name', max_length=255)),
            ],
            options={
                'db_table': 'submissions_course',
            },
        ),
    ]
