# Generated by Django 6.0.1 on 2026-02-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Submissions', '0015_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetotp',
            name='last_resent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passwordresetotp',
            name='resend_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='passwordresetotp',
            name='otp_code',
            field=models.CharField(max_length=256),
        ),
    ]
