# Generated by Django 6.0.1 on 2026-02-05 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Submissions', '0017_team_preference_system'),
    ]

    operations = [
    ]
