# Generated by Django 6.0.1 on 2026-02-11 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Submissions', '0018_schema_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapstoneClientCompletionLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('team_id', models.CharField(blank=True, db_column='team_id', max_length=50, null=True)),
                ('student_email', models.EmailField(blank=True, db_column='student_email', max_length=255, null=True)),
                ('student_name', models.CharField(blank=True, db_column='student_name', max_length=255, null=True)),
                ('csv_s3_key', models.CharField(db_column='csv_s3_key', default='reports/completed-projects.csv', help_text='S3 path where CSV is stored', max_length=500)),
                ('generated_at', models.DateTimeField(auto_now_add=True, db_column='generated_at', help_text='When record was added to CSV')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('duplicate', 'Duplicate - Already Exported')], db_column='status', default='success', max_length=20)),
                ('batch_id', models.CharField(blank=True, db_column='batch_id', help_text='CSV generation batch identifier (for grouping)', max_length=100, null=True)),
                ('error_message', models.TextField(blank=True, db_column='error_message', null=True)),
            ],
            options={
                'db_table': 'submissions_capstone_client_completion_log',
            },
        ),
        migrations.CreateModel(
            name='LocalFileDeletionLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('local_path', models.CharField(db_column='local_path', max_length=1000)),
                ('deleted_at', models.DateTimeField(auto_now_add=True, db_column='deleted_at')),
                ('status', models.CharField(choices=[('success', 'Deleted Successfully'), ('failure', 'Deletion Failed'), ('not_found', 'File Not Found')], db_column='status', default='success', max_length=20)),
                ('error_message', models.TextField(blank=True, db_column='error_message', null=True)),
            ],
            options={
                'db_table': 'submissions_local_file_deletion_log',
            },
        ),
        migrations.CreateModel(
            name='S3ToLocalMoveLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('team_id', models.CharField(blank=True, db_column='team_id', max_length=50, null=True)),
                ('project_id', models.CharField(blank=True, db_column='project_id', max_length=50, null=True)),
                ('original_s3_path', models.CharField(db_column='original_s3_path', help_text='Original path in S3 bucket', max_length=500)),
                ('local_path', models.CharField(db_column='local_path', help_text='Destination path on local server', max_length=1000)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_column='timestamp', help_text='When file was moved')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('partial', 'Partial')], db_column='status', default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, db_column='error_message', help_text='Error details if move failed', null=True)),
                ('file_size_bytes', models.BigIntegerField(blank=True, db_column='file_size_bytes', help_text='Size of file in bytes', null=True)),
                ('attempt_count', models.PositiveIntegerField(db_column='attempt_count', default=1, help_text='Number of retry attempts made')),
            ],
            options={
                'db_table': 'submissions_s3_to_local_move_log',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='status_updated_at',
            field=models.DateTimeField(blank=True, db_column='status_updated_at', help_text='Timestamp when student status was last updated', null=True),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='team',
            field=models.ForeignKey(db_column='TeamID', on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='Submissions.team', to_field='team_id'),
        ),
        migrations.AlterField(
            model_name='student',
            name='team',
            field=models.ForeignKey(blank=True, db_column='TeamID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrolled_students', to='Submissions.team', to_field='team_id'),
        ),
        migrations.AlterField(
            model_name='team',
            name='course',
            field=models.CharField(db_column='course', default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='team',
            name='created_at',
            field=models.DateTimeField(blank=True, db_column='created_at', help_text='Timestamp when team_id was assigned', null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='email_sent',
            field=models.BooleanField(db_column='email_sent', default=False, help_text='Whether team formation email was sent'),
        ),
        migrations.AlterField(
            model_name='team',
            name='preference_emails',
            field=models.JSONField(blank=True, db_column='preference_emails', default=list, help_text='List of teammate emails (max 3)', null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='preference_submitted_at',
            field=models.DateTimeField(auto_now_add=True, db_column='preference_submitted_at', null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_count',
            field=models.PositiveIntegerField(db_column='team_count', default=1),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_id',
            field=models.CharField(blank=True, db_column='team_id', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_preference',
            field=models.CharField(choices=[('individual', 'Individual'), ('i_have_team', 'I have a team'), ('assign_team', 'Assign a team')], db_column='team_preference', default='individual', max_length=20),
        ),
        migrations.AlterField(
            model_name='teamproject',
            name='team',
            field=models.ForeignKey(db_column='TeamID', on_delete=django.db.models.deletion.CASCADE, related_name='team_projects', to='Submissions.team', to_field='team_id'),
        ),
        migrations.AddField(
            model_name='capstoneclientcompletionlog',
            name='student',
            field=models.ForeignKey(blank=True, db_column='student_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='csv_completion_logs', to='Submissions.student'),
        ),
        migrations.AddField(
            model_name='s3tolocalmovelog',
            name='submission',
            field=models.ForeignKey(blank=True, db_column='submission_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='s3_move_logs', to='Submissions.submission'),
        ),
        migrations.AddField(
            model_name='localfiledeletionlog',
            name='move_log',
            field=models.ForeignKey(db_column='move_log_id', on_delete=django.db.models.deletion.CASCADE, related_name='deletion_logs', to='Submissions.s3tolocalmovelog'),
        ),
        migrations.AddIndex(
            model_name='capstoneclientcompletionlog',
            index=models.Index(fields=['status'], name='submissions_status_01eb39_idx'),
        ),
        migrations.AddIndex(
            model_name='capstoneclientcompletionlog',
            index=models.Index(fields=['generated_at'], name='submissions_generat_cae747_idx'),
        ),
        migrations.AddIndex(
            model_name='capstoneclientcompletionlog',
            index=models.Index(fields=['student'], name='submissions_student_53f3de_idx'),
        ),
        migrations.AddIndex(
            model_name='capstoneclientcompletionlog',
            index=models.Index(fields=['team_id'], name='submissions_team_id_a24241_idx'),
        ),
        migrations.AddConstraint(
            model_name='capstoneclientcompletionlog',
            constraint=models.UniqueConstraint(fields=('student', 'csv_s3_key'), name='uniq_student_csv_entry'),
        ),
        migrations.AddIndex(
            model_name='s3tolocalmovelog',
            index=models.Index(fields=['status'], name='submissions_status_617b8c_idx'),
        ),
        migrations.AddIndex(
            model_name='s3tolocalmovelog',
            index=models.Index(fields=['timestamp'], name='submissions_timesta_a617ea_idx'),
        ),
        migrations.AddIndex(
            model_name='s3tolocalmovelog',
            index=models.Index(fields=['team_id'], name='submissions_team_id_c28abd_idx'),
        ),
        migrations.AddIndex(
            model_name='s3tolocalmovelog',
            index=models.Index(fields=['project_id'], name='submissions_project_56d1b1_idx'),
        ),
        migrations.AddIndex(
            model_name='s3tolocalmovelog',
            index=models.Index(fields=['status', 'timestamp'], name='submissions_status_8fd287_idx'),
        ),
        migrations.AddIndex(
            model_name='localfiledeletionlog',
            index=models.Index(fields=['status'], name='submissions_status_dde6d0_idx'),
        ),
        migrations.AddIndex(
            model_name='localfiledeletionlog',
            index=models.Index(fields=['deleted_at'], name='submissions_deleted_4a07b9_idx'),
        ),
    ]
