# Generated by Django 4.2.29 on 2026-04-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Submissions', '0025_course_alias_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVUploadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('admin_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_students', models.JSONField(blank=True, default=list)),
                ('created_identities', models.JSONField(blank=True, default=list)),
                ('modified_students', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'CSV Upload Log',
                'verbose_name_plural': 'CSV Upload Logs',
                'db_table': 'submissions_csv_upload_log',
                'ordering': ['-timestamp'],
            },
        ),
    ]
