# Generated by Django 4.2.29 on 2026-04-07 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Submissions', '0027_delete_adminuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvuploadlog',
            name='modified_identities',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
