# Generated by Django 4.2.29 on 2026-04-27 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Submissions', '0031_backfill_student_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('Registered', 'Registered'), ('TeamIDGiven', 'TeamIDGiven'), ('CapStoneProjectsAssigned', 'CapStoneProjectsAssigned'), ('ReadyForClientPick', 'ReadyForClientPick'), ('ClientProjectAssigned', 'ClientProjectAssigned'), ('AllCompleted', 'AllCompleted'), ('CDSCycleComplete', 'CDSCycleComplete'), ('AIECapstoneAssigned', 'AIECapstoneAssigned'), ('AIEReadyForClientPick', 'AIEReadyForClientPick'), ('AIEClientAssigned', 'AIEClientAssigned'), ('LegacyArchived', 'LegacyArchived')], db_column='status', default='Registered', max_length=40),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_preference',
            field=models.CharField(choices=[('individual', 'Individual'), ('assign_team', 'Assign a team')], db_column='team_preference', default='individual', max_length=500),
        ),
    ]
